#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

FROM ubuntu:20.04

RUN apt-get update ||	apt-get update
RUN apt-get install --yes make curl

RUN adduser --disabled-login --gecos "" btcuser

USER btcuser
WORKDIR /home/btcuser

COPY --chown=btcuser scripts/install-bitcoin.sh /tmp/install-bitcoin.sh
RUN /tmp/install-bitcoin.sh 0.18.1

COPY --chown=btcuser src/main/resources/bitcoin-docker.conf /home/btcuser/btcData/

WORKDIR /home/btcuser/btcData

EXPOSE 19091
ENTRYPOINT /home/btcuser/.bitcoin/bitcoin-0.18.1/bin/bitcoind -datadir=/home/btcuser/btcData -conf=/home/btcuser/btcData/bitcoin-docker.conf
