#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

FROM openjdk:8-jre-alpine

WORKDIR /home/sdk

COPY target/inventory-management-docker.jar inventory-management-docker.jar
COPY target/lib/* /home/sdk/lib/
COPY src/main/resources/secretKeyStore.regtest.txt src/main/resources/secretKeyStore.regtest.txt

ENTRYPOINT java -jar inventory-management-docker.jar -s ${SANDBOX_HOST} -p ${SANDBOX_PORT} -b ${BITCOIN_HOST} -bp ${BITCOIN_PORT} -busername ${BITCOIN_USERNAME} -bpassword ${BITCOIN_PASSWORD}
