#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

FROM ubuntu:20.04

RUN apt-get update ||	apt-get update
RUN apt-get install --yes make curl

RUN adduser --disabled-login --gecos "" btcuser

# run following commands from user's home directory
WORKDIR /home/btcuser

ADD src/main/resources/bitcoin.conf /home/btcuser/btcData/

RUN chown -R btcuser:btcuser /home/btcuser/btcData

USER btcuser

COPY --chown=btcuser scripts/install-bitcoin.sh /tmp/install-bitcoin.sh
RUN /tmp/install-bitcoin.sh 0.18.1

WORKDIR /home/btcuser/btcData

EXPOSE 19091
CMD ["/home/btcuser/.bitcoin/bitcoin-0.18.1/bin/bitcoind","-datadir=/home/btcuser/btcData"]
