#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

DATADIR=$(mktemp -d)

CONF="$(pwd)/src/main/resources/bitcoin-standalone.conf"

exec bitcoind -datadir="$DATADIR" -conf="$CONF"
